name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: |
          npm install -g @coral-xyz/anchor-cli

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "explorer/package-lock.json"

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint Rust code
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Build Rust workspace
        run: cargo build --verbose

      - name: Run Rust unit tests
        run: cargo test --verbose --workspace --lib

      - name: Run Rust integration tests
        run: cargo test --verbose --workspace --test '*'

      - name: Install Node dependencies (root)
        run: npm ci

      - name: Run TypeScript compilation check
        run: npx tsc --noEmit

      - name: Install Node dependencies (explorer)
        run: |
          cd explorer
          npm ci

      - name: Run explorer tests
        run: |
          cd explorer
          npm run type-check

      - name: Build explorer
        run: |
          cd explorer
          npm run build

      - name: Test Anchor programs (if anchor installed successfully)
        run: |
          if command -v anchor &> /dev/null; then
            anchor test --skip-local-validator
          else
            echo "Anchor CLI not available, skipping anchor tests"
          fi

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security audit
        run: |
          cargo audit || echo "Cargo audit completed with warnings"

      - name: Check for sensitive files
        run: |
          if find . -name "*.key" -o -name "*.pem" -o -name "id.json" | grep -v target | head -1; then
            echo "Warning: Potential sensitive files found"
            exit 1
          fi
